plugins:
  layouts_site_info_enabled:
    default: false
    client: true

  layouts_site_info_copyright:
    default: true
    client: true

  layouts_site_info:
    default: ''
    textarea: true
    client: true
